title: Blog
tagline: Bangundwir
description: Content-focused template for a blog hosted on GitHub Pages.
url: https://blog.banguncenter.my.id/

author:
  name: Bangundwir
  url: https://twitter.com/bangundwir
  email: bangundwir@gmail.com

# GitHub Pages / Jekyll configuration
baseurl: ""
permalink: /:title/
paginate: 5
defaults:
  - scope:
      path: ""
    values:
      layout: post
