title: Blog
tagline: BangunCenter
description: Blog ini sebagai wadah untuk menceritakn apapun yang ingin ceritakan
url: https://blog.banguncenter.my.id/

author:
  name: BangunCenter
  url: https://twitter.com/bangundwir
  email: bangundwir@gmail.com

# GitHub Pages / Jekyll configuration
baseurl: ""
permalink: /:title/
paginate: 5
defaults:
  - scope:
      path: ""
    values:
      layout: post
